apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: progest
  title: "progest"
  description: "Sistema hospitalar integrado para controle de estoques, rastreabilidade de lotes com critério FIFO/FEFO, dispensação setorial e gestão de medicamentos controlados (Portaria 344/98 e SIMPAS)."
  annotations:
    github.com/project-slug: "chvcti/backend-progest-base"
    backstage.io/techdocs-ref: "dir:."
spec:
  owner: user:ifba
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: progest-base-mysql-db
  title: "progest-base-mysql-db"
  description: "Recurso backend-progest-base-mysql-db (database)"
  tags:
    - mysql
  annotations:
    github.com/project-slug: "chvcti/backend-progest-base"
spec:
  type: database
  lifecycle: experimental
  owner: user:ifba
  system: progest
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: progest-base-redis-cache
  title: "progest-base-redis-cache"
  description: "Recurso backend-progest-base-redis-cache (cache)"
  tags:
    - redis
  annotations:
    github.com/project-slug: "chvcti/backend-progest-base"
spec:
  type: cache
  lifecycle: experimental
  owner: user:ifba
  system: progest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: progest-backend-base
  title: "progest-backend-base"
  description: "Núcleo de regras de negócio, persistência de dados e segurança do ecossistema hospitalar ProGest. Desenvolvido em **PHP 8.2** sobre o framework **Laravel 10**, a aplicação é responsável pelo gerenciamento de estoques, rastreabilidade física de lotes por critério FIFO/FEFO, dispensação assistencial para enfermarias e UTIs, cadeia de ressuprimento hospitalar e conformidade regulatória com a **Portaria SVS/MS nº 344/1998** e com o catálogo **SIMPAS Bahia**."
  annotations:
    github.com/project-slug: "chvcti/backend-progest-base"
spec:
  type: service
  lifecycle: experimental
  owner: user:ifba
  system: progest
  dependsOn:
    - resource:default/backend-progest-base-mysql-db
    - resource:default/backend-progest-base-redis-cache
