apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backend-progest-base
  title: "backend-progest-base"
  description: "Sistema backend-progest-base analisado automaticamente"
  annotations:
    github.com/project-slug: "chvcti/backend-progest-base"
    backstage.io/techdocs-ref: "dir:."
spec:
  owner: user:ifba
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backend-progest-base-mysql-db
  title: "backend-progest-base-mysql-db"
  description: "Recurso backend-progest-base-mysql-db (database)"
  tags:
    - mysql
  annotations:
    github.com/project-slug: "chvcti/backend-progest-base"
spec:
  type: database
  lifecycle: experimental
  owner: user:ifba
  system: backend-progest-base
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backend-progest-base-redis-cache
  title: "backend-progest-base-redis-cache"
  description: "Recurso backend-progest-base-redis-cache (cache)"
  tags:
    - redis
  annotations:
    github.com/project-slug: "chvcti/backend-progest-base"
spec:
  type: cache
  lifecycle: experimental
  owner: user:ifba
  system: backend-progest-base
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-progest-base
  title: "backend-progest-base"
  description: "Componente backend-progest-base-backend (service)"
  annotations:
    github.com/project-slug: "chvcti/backend-progest-base"
    backstage.io/techdocs-ref: "dir:."
spec:
  type: service
  lifecycle: experimental
  owner: user:ifba
  system: backend-progest-base
  dependsOn:
    - resource:default/backend-progest-base-mysql-db
    - resource:default/backend-progest-base-redis-cache